### ISSUE TITLE
horoscope.css, example.css

### ISSUE THREAD

**Issue by erenozkul** [slissner/HoroscopeDrawer#4]
Hi, not included horoscope.css and example.css on dist or example folder. chart look like big black dot

**Comment by slissner** [comment]
Hi @erenozkul! Have you found a solution in the meantime?

I have not forgotten the issue. Currently I am very busy with job and stuff, but the moment I will have some time, I will revise your issue.

**Comment by erenozkul** [comment]
Hi @slissner, didn't resolved the problem, we use to another package.

**Comment by slissner** [comment]
Perhaps solved by #5
