### ISSUE TITLE
Missing example.js and css files from /example

### ISSUE THREAD

**Issue by brandonreid** [slissner/HoroscopeDrawer#5]
Hi @slissner 

Thanks so much for making this!

I haven't been able to get a build going locally unfortunately. I realize this might be a retired project for you, but I'd sure love to be able to fire it up.

When I run `gulp example-build`, it looks like the `/dist` and `/example` folders are missing stylesheets and `example.js`, I can't actually find them in the repo either. Maybe you've got some code locally you haven't pushed?

Anyway, thanks again, if all else fails I'll just have to dig in to the functions and see if I can't make something happen.

**Comment by brandonreid** [comment]
Ah, figured out I can use your example js from the readme and manually make an `example.js` file. Styles file would still be great, but I do have a chart showing! 🎉

**Comment by brandonreid** [comment]
Ah, I see.. Because `/example` is in the `.gitignore` file, the `src/example` folder wasn't added to the commit. PR otw!

**Comment by slissner** [comment]
Hi @brandonreid ! Thanks for having interest in this code. Indeed, I worked on this as a hobby project some months ago and unfortunately, do not find time at all to get back to the horoscopes. I will review your PR asap!
